services:
  mongodb:
    image: mongo
    ports:
      - "2717:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
